### ISSUE TITLE
Usage of clam.py with multiple files

### ISSUE THREAD

**Issue by luamfb** [seahorn/clam#101]
Hello, thank you for maintaining this project.

Attempting to use the helper script `clam.py` with several input files fails with this message:

```
$ clam.py a.c b.c

Platform: Linux 6.8.0-40-generic
LLVM version: 14.0
usage: clam.py [...]
clam.py: error: unrecognized arguments: b.c
```

I know I could manually compile each file to LLVM bitcode and link them all, but with large projects this process becomes a burden. I'd like to know if there's a way to do it directly.

**Comment by caballa** [comment]
For large projects, the way to go is the use of gclang  https://github.com/SRI-CSL/gllvm.
gclang allows you to generate a single bitcode file from an arbitrary project as long as it uses standard build systems such as make or cmake. 

For instance, for a project that uses `make` and generates the executable `myexecutable`, using gclang can be as easy as:

```
CC=gclang  ./configure
make
make install
```

And then, just type `get-bc myexecutable` where `myexecutable` is in the install directory. 
This will generate a file `myexecutable.bc` that you can pass to `clam.py`. 
The only thing that you have to make sure is that gclang points to clang-14 (see gclang doc for that). 
I also typically pass `-O1` because clam.py might not like -O2 or -O3 and prefers to do its own optimizations. 

```
CC=gclang  CFLAGS="-O1" ./configure
make
make install
```

Let me know if you have more questions. I have used gclang many times in the past to analyze multiple real projects and it was really easy 99% of the cases.

**Comment by luamfb** [comment]
I see, I'll try out `gclang`. Thank you!
