### ISSUE TITLE
Interprocedural Invariants 

### ISSUE THREAD

**Issue by shankarapailoor** [seahorn/clam#38]
Hi, 

I have a simple C program like the following:

```C
#include <unistd.h>

int add (int a) {
	if (a > 2)
		a += 4;
	else
		a += 2;
	write(1, "Hello", a);
	return a;
}

int main(int argc, char **argv) {
	int x = 4;
	add(x);
	return 0;
}
```

I generated the IR for this program and ran crabllvm with the following arguments:

```bash
./crabllvm -crab-inter -crab-print-invariants -crab-track=arr -crab-heap-analysis=cs-sea-dsa input.bc 
```

I expected crab to say that ```a = [4, 4]``` holds at the entry to ```add``` but it says that no invariants hold. Am I correct in this expectation? Thanks!

EDIT: It seems if we change the program to do just ```add(4)``` instead of ```add(x)``` I see the invariant but I'm not sure if that is to be expected.

**Comment by caballa** [comment]
If I analyze directly your C program with `crabllvm.py` using this command 
` crabllvm.py -O0 test-inter.c --crab-inter --crab-track=arr --crab-heap-analysis=cs-sea-dsa` I get the expected result:

```
crabllvm.py -O0 test-inter.c --crab-inter --crab-track=arr --crab-heap-analysis=cs-sea-dsa

.0:int declare add(:int)
_2:
/**
  INVARIANTS: ({}, { -> [4, 4]})
**/
  .0.v = ite(- <= -3,4,2);
  .0 = .0.v+;
  _4 = &(.str) + 0;
  havoc(_ret);
  return .0;
/**
  INVARIANTS: ({}, {.0.v -> [4, 4],  -> [4, 4], .0 -> [8, 8]})
**/


@V_10:int declare main(:int,:ptr)
_3:
/**
  INVARIANTS: ({}, {})
**/
  @V_8 = 4;
  _ret = call add(@V_8:int);
  @V_10 = 0;
  return @V_10;
/**
  INVARIANTS: ({}, {@V_8 -> [4, 4], @V_10 -> [0, 0], _ret -> [6, 8]})
**/
```

Maybe your bitcode is optimized? Can you share your bitcode?

**Comment by shankarapailoor** [comment]
Hi!

[Here](https://drive.google.com/file/d/1nb4TcNJVHaivAleDh0oTvBkhMq7s2WzY/view?usp=sharing) is the bitcode.

**Comment by caballa** [comment]
The short answer is that your bitcode has the attribute `optnone` in all functions. 
As a result, the pass `mem2reg` has no effect. This pass is the one that converts the program in SSA form and more importantly for crab, lowers stack variables to LLVM registers. 

Having said this, crab can (in principle) handle code even if `mem2reg` is not run although things will be harder. I explain below (*) the challenges in case you are interested.

Is there a particular reason why you want to analyze this program with `optnone`? Since clang 5.0 if you just add `-O0` then it will add `optnone` to all functions. You need to add the flags `-Xclang -disable-O0-optnone` to avoid adding `optnone` attribute.  If you call directly `crabllvm.py` then it will add those flags automatically for you.

(*) The analysis is  imprecise because most LLVM operations are translated to array operations in    Crab.  The current array domain in Crab is just array smashing. 
Array smashing always performs weak updates for all `array_store` crab statements. The only way for array smashing to return something different from top is to have a crab statement `array_init` which sets the initial value for all array values and then each `array_store` performs a weak update. 
The binary `crabllvm` does not add `array_init` statements. The preprocessor `crabllvm-pp` is the one that might add some `array_init` statements.

**Comment by shankarapailoor** [comment]
Thanks alot for the explanation! Following your instructions I see the expected invariant at the function entry.
