### ISSUE TITLE
Analyzing FP programs questions

### ISSUE THREAD

**Issue by joaoriverd** [seahorn/clam#61]
Hi there!

I'm trying to implement static analysis of floating-point programs. So far when I try to use clam.py float_test.c I don't get any invariant (which makes sense since it only works on integers). I was wondering if I can get some pointers on what would be required to support FP variables in clam so I can try to implement it if possible.

Thank you for all the help!

**Comment by caballa** [comment]
Yes, unfortunately Clam does not support floating points. 

To support FP,  we would need three things:

1) [Crab] Extend CrabIR (the IR used by Clam) to support FP operands and instructions
2) [Crab] An abstract domain that reasons about FP numbers.
3) [Clam] Translate LLVM FP instructions to CrabIR FP instructions

Regarding 2)  if you just want to infer intervals but being sound on FP semantics then I would recommend to look at this paper: 

Relational Abstract Domains for the Detection of Floating-Point Run-Time Errors. [ESOP 2004](https://dblp.org/db/conf/esop/esop2004.html#Mine04): 3-17

Which kind of applications are you interested in? 
I ask it because before implementing anything I would be sure that the goal you have in mind is plausible since reasoning about FP is hard.

**Comment by dengyuhui14** [comment]
Hi there!

What should I do if I want to modify the files in apron library?  I install clam using -DCRAB_USE_APRON=ON. I wonder whether the changes I make on apron files will take effect when I run clam.py.

Thank you for all the help!

**Comment by caballa** [comment]
I hope I didn't scare you. I'll close this issue for now. Feel free to re-open it if you have more questions.
