### ISSUE TITLE
question about --crab-bounds-check

### ISSUE THREAD

**Issue by bjjwwang** [seahorn/clam#69]
Hi Seahorn Team,

Q1: is --crab-bounds-check for buffer overflow?
Q2: I don't find documentation regarding this option, is it deprecated?
Q3: I open this option but return `-- Inserted 0 bound checks` every time, Do I need to insert something to source code to enable it?

Thank you.

**Comment by caballa** [comment]
Hi @bjjwwang , thank you for using clam. 

You are right that there is no documentation. I'll try to add some soon. 
The only kind of documentation is to type `clam.py --help`:

```
  --crab-check {none,assert,null-legacy,null,uaf-legacy,uaf,bounds,is-deref}
                        Check properties (default none):
                        - assert: user-defined assertions via __CRAB_assert
                        - null-legacy: insert __CRAB_assert calls in LLVM IR for null dereference errors
                        - null: insert CrabIR assertions for null dereference errors
                        - uaf-legacy: insert __CRAB_assert calls in LLVM IR for use-after-free errors
                        - uaf: insert CrabIR assertions for use-after-free errors
                        - bounds: insert CrabIR assertions and ghost code for buffer overflow errors
                          (instrumentation is not complete: lack of modeling pointers stored in memory)
                        - is-deref: insert CrabIR assertions for proving that calls to LLVM function sea.is_dereferenceable cannot fail
                          (this option is used mostly by SeaHorn which adds the calls to sea.is_dereferenceable)
```

The option `bounds` in `clam.py` corresponds to the the `clam` executable option `--crab-bounds-check` that you are referring to. This option is kind of deprecated because it's incomplete. This option will add at the CrabIR level (Clam translates LLVM IR to CrabIR) some extra code to be able to check for buffer overflows. The instrumentation adds two special variables per pointer (one to keep track of the size of the memory object and another for the pointer offset). As I said, the problem with this instrumentation is that it's incomplete because it does not instrument a pointer that is read from memory. Nevertheless, if you have a small example where you think it should add some instrumentation you can share it with me and I'll take a look.
                          
I strongly recommend to use the option `is-deref`. This one does not add any extra variables to keep track of pointer offsets and sizes. Instead, it runs a special abstract domain in Crab that keeps track of those as part of the abstract domain. The only caveat is that you need to write a LLVM pass to adds calls to a special function `sea.is_dereferenceable`. But add them should be straightforward. One example is done in SeaHorn (https://github.com/seahorn/seahorn/blob/dev14/lib/Transforms/Instrumentation/FatBufferBoundsCheck.cc). The C definition of `sea.is_dereferenceable` is here (https://github.com/seahorn/seahorn/blob/dev14/include/seahorn/seahorn.h#L35). You can also add calls to this special function directly in the C program  if you just care about running small tests for now.

**Comment by caballa** [comment]
Let me know if you have more questions. I'll close this issue for now

**Comment by bjjwwang** [comment]
I am still studying that. thank you so much for your answer.
